docs: improve readme file
guidesmiths/cuckoojs pull request #13
Opened 2022-10-26 14:14 UTC by dustytrinkets

## What’s the focus of this PR
This PR is focused on updating the readme file so it's easier to get started with cuckoojs.
WIP please add anything you feel is needed 

## How to review this PR
Think yourself as someone who doesn't know what cuckoo is or how to use it. What would you like to find here?

Before submitting this PR, I made sure:

[x] The code builds clean without any errors or warnings
[x] I'm using our guidelines
[ ] I've added unit tests if feasible

2022-10-26 15:21 UTC, neodmy approved these changes
👍

2022-10-27 08:03 UTC, ardguezsoc approved these changes

2022-10-27 08:03 UTC, ardguezsoc commented on README.md
> +#####Let the cuckoo accommodate the nest for you.
![Screenshot 2022-10-27 at 10 02 50 AM](https://user-images.githubusercontent.com/79102959/198226860-ea63cdfa-9f46-4b39-949b-3a37f9b39237.png)
see how it is current displayed

2022-10-27 09:41 UTC, dustytrinkets commented on README.md
> +#####Let the cuckoo accommodate the nest for you.
thanks!

2022-10-27 11:17 UTC, inigomarquinez commented on README.md
> +##### Let the cuckoo accommodate the nest for you.
LOVING THIS! ❤️

2022-10-27 11:22 UTC, inigomarquinez requested changes
Great work.

Some suggestions added :)

2022-10-27 11:22 UTC, inigomarquinez commented on README.md
> +### <img alt="logo" src="./assets/logo.svg" width="20px" />  How to use
```suggestion
### <img alt="logo" src="./assets/logo.svg" width="20px" />  How to use it
```

2022-10-27 11:22 UTC, inigomarquinez commented on README.md
>  ```bash
Perhaps we can add a description for the command, such as:

```suggestion
```bash
Creating a new NestJS app with the basic tooling:
```

2022-10-27 11:22 UTC, inigomarquinez commented on README.md
> +
Perhaps we can add some examples:
```suggestion
cuckoo generate|g controller <name>
```

2022-10-27 11:35 UTC, dustytrinkets commented on README.md
> +
nice!

2022-10-27 15:02 UTC, merged